# se led training configuration
[[configs]]
type = ""
model_name = ""
deployment_name = ""
api_endpoint = ""
api_key = ""
api_version = ""
# mini
[[configs]]
type = ""
model_name = ""
deployment_name = ""
api_endpoint = ""
api_key = ""
api_version = ""
